"""Agent 4 — Humanization Engine: makes content sound naturally human."""
from services.llm import complete
import logging

log = logging.getLogger("ai-engine.humanizer")

SYSTEM = """You are a master editor who transforms content into naturally human-written prose.
Goal: make content feel like it was written by a thoughtful, experienced professional —
not generated by AI.
Preserve all facts, data, and strategic meaning. Only change HOW it's expressed.
Never fabricate information, statistics, or anecdotes."""

# ─── AI Phrase Blacklist ──────────────────────────────────────────────────────

BANNED_AI_PHRASES = [
    # Opening clichés
    "In today's fast-paced world",
    "In today's rapidly evolving",
    "In an era of",
    "In the age of",
    "It is important to note",
    "It's worth noting that",
    "It goes without saying",
    "Needless to say",

    # Transitions
    "In conclusion",
    "To summarize",
    "To recap",
    "In summary",
    "As we can see",
    "As mentioned above",
    "As previously discussed",
    "Furthermore",
    "Moreover",
    "Additionally",
    "In addition to this",

    # Corporate buzzwords
    "Game-changing",
    "Groundbreaking",
    "Revolutionary",
    "Transformative",
    "Disruptive",
    "Unprecedented",
    "Paradigm shift",
    "Synergy",
    "Ecosystem",
    "Leverage",
    "Utilize",
    "Operationalize",
    "Circle back",
    "Touch base",
    "Move the needle",
    "Low-hanging fruit",
    "Boil the ocean",
    "Peel back the layers",
    "Unpack",
    "Double-click on",

    # AI tells
    "Robust",
    "Seamless",
    "Holistic",
    "Cutting-edge",
    "State-of-the-art",
    "Best-in-class",
    "World-class",
    "Best practices",
    "Deep dive",
    "Delve into",
    "Nuanced understanding",
    "Comprehensive overview",
    "Landscape",
    "Tapestry",
    "Realm of",
    "In the world of",
    "At the end of the day",
    "When it comes to",
    "The reality is",
    "It's no secret that",

    # Enthusiasm tells
    "Excited to share",
    "Thrilled to announce",
    "Delighted to present",
    "I am pleased to",
    "We are excited to",
]

# ─── Intensity Instructions ───────────────────────────────────────────────────

INTENSITY_RULES = {
    "light": {
        "description": "Minimal changes — surgical removal of AI tells only.",
        "rules": [
            "Remove ONLY the most obvious AI clichés from the banned list",
            "Keep sentence structure and rhythm largely intact",
            "Preserve all formatting, headings, and paragraph breaks",
            "Do NOT restructure — only spot-fix robotic phrases",
        ],
        "temperature": 0.5,
    },
    "medium": {
        "description": "Balanced humanization — natural flow with preserved structure.",
        "rules": [
            "Remove ALL banned AI phrases — replace with natural, specific alternatives",
            "Vary sentence lengths — mix short (5-8 words) with longer ones",
            "Add subtle rhythm variation — not every paragraph the same length",
            "Use contractions naturally (it's, you'll, we're) — but not forced",
            "Replace generic adjectives with specific, concrete ones",
            "Occasional conversational aside is fine (e.g., 'Here's the thing:')",
            "Maintain professional tone throughout",
            "Do not add fabricated details",
        ],
        "temperature": 0.65,
    },
    "aggressive": {
        "description": "Maximum humanization — rewrite for authentic human voice.",
        "rules": [
            "Substantially rewrite for naturalness — don't just swap phrases",
            "Dramatically vary sentence lengths and structures throughout",
            "Break some grammar rules intentionally for voice (fragments are fine)",
            "Add micro-observations or brief qualifiers (e.g., 'at least in my experience')",
            "Use casual asides sparingly: 'honestly,' 'look,' 'here's the thing'",
            "Mix active and passive voice naturally — don't force everything active",
            "End thoughts abruptly sometimes — humans trail off",
            "Remove ALL corporate enthusiasm — no 'excited to share' etc.",
            "Replace 'A is B' reductive statements with nuanced phrasing",
            "Cut all filler openers and transitions — just jump to the point",
            "Result should feel like a thoughtful person wrote it from scratch",
        ],
        "temperature": 0.72,
    },
}

# ─── Language-Specific Rules ──────────────────────────────────────────────────

LANGUAGE_RULES = {
    "Hindi": "Apply humanization rules while writing in Hindi. Use natural Hindi idioms and phrasing.",
    "Hinglish": (
        "Content is in Hinglish (Hindi-English mix). "
        "Humanize in a way that feels natural to Indian professionals — "
        "casual Hindi expressions mixed with English are expected and welcome."
    ),
    "Spanish": "Apply humanization in Spanish. Use natural Spanish phrasing and avoid direct translations from English.",
    "French": "Apply humanization in French. Use natural French phrasing.",
}

# ─── Tonality Integration ─────────────────────────────────────────────────────

TONALITY_HUMANIZE_RULES = {
    "angry":      "Let measured indignation show through word choice — sharp edges, not explosive.",
    "frustrated": "Slight exasperation in sentence rhythm — shorter, more clipped phrasing.",
    "excited":    "Genuine energy — varied punctuation, some short punchy sentences.",
    "confident":  "Declarative statements — minimal hedging, direct assertions.",
    "curious":    "Questions and wondering — invite the reader to think alongside you.",
    "empathetic": "Warmer language — 'I understand...', 'Many of us have...'",
    "playful":    "Light wordplay, the occasional unexpected word choice.",
    "serious":    "Measured pacing, weighty words — no lightness or humor.",
}

# ─── Prompt Template ──────────────────────────────────────────────────────────

USER_TEMPLATE = """Humanize the following content.

CONTENT:
{content}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HUMANIZATION INTENSITY: {intensity_upper}
{description}

RULES TO APPLY:
{rules_block}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
BANNED AI PHRASES — eliminate every instance:
{banned_block}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{tonality_block}
{language_block}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ABSOLUTE RULES:
- Keep ALL facts, statistics, names, and data exactly as they are
- Do NOT add invented anecdotes, statistics, or claims
- Do NOT reduce total content length by more than 10%
- Preserve the overall structure (headings, sections, key points)

OUTPUT: Write only the humanized content. No commentary, no labels."""


# ─── Agent Entry Point ────────────────────────────────────────────────────────

async def run(
    content:          str,
    intensity:        str  = "medium",
    tonality:         dict = None,
    language:         str  = "English",
    brand_phrases:    list = None,
) -> dict:
    """
    Humanize content.

    Args:
        content:       Text to humanize
        intensity:     light | medium | aggressive
        tonality:      Tonality spectrum dict (from content wizard)
        language:      Output language
        brand_phrases: Additional brand-banned phrases to include
    """
    # Validate intensity
    if intensity not in INTENSITY_RULES:
        log.warning("Invalid intensity '%s' — defaulting to medium", intensity)
        intensity = "medium"

    rules_config = INTENSITY_RULES[intensity]

    # ── Build banned phrases list ─────────────────────────────────────────────
    all_banned = list(BANNED_AI_PHRASES)
    if brand_phrases:
        # Add brand-specific banned phrases (dedup)
        for phrase in brand_phrases:
            if phrase not in all_banned:
                all_banned.append(phrase)

    banned_block = "\n".join(f"  • {p}" for p in all_banned)
    rules_block  = "\n".join(f"  {i+1}. {r}" for i, r in enumerate(rules_config["rules"]))

    # ── Tonality block ────────────────────────────────────────────────────────
    tonality_lines = []
    if tonality:
        active = [
            (k, v) for k, v in tonality.items()
            if v >= 5 and k in TONALITY_HUMANIZE_RULES
        ]
        active.sort(key=lambda x: x[1], reverse=True)

        if active:
            tonality_lines.append("TONALITY TO REFLECT IN HUMANIZATION:")
            for tone, val in active[:4]:  # Top 4 tones only
                rule = TONALITY_HUMANIZE_RULES[tone]
                tonality_lines.append(f"  • {tone.upper()} ({val}/10): {rule}")

    tonality_block = "\n".join(tonality_lines) if tonality_lines else ""

    # ── Language block ────────────────────────────────────────────────────────
    lang_instruction = LANGUAGE_RULES.get(language, "")
    language_block = (
        f"LANGUAGE NOTE: {lang_instruction}"
        if lang_instruction
        else f"Language: {language} — apply all rules in this language."
    )

    # ── Estimate max tokens ───────────────────────────────────────────────────
    content_words = len(content.split())
    # Humanization can be longer than input — allow 120%
    max_tok = min(int(content_words * 1.5) + 600, 6000)

    log.info(
        "Humanizer | intensity=%s | content_words=%d | lang=%s | tonality_active=%s",
        intensity,
        content_words,
        language,
        [k for k, v in (tonality or {}).items() if v >= 5],
    )

    user_prompt = USER_TEMPLATE.format(
        content=content,
        intensity_upper=intensity.upper(),
        description=f"Goal: {rules_config['description']}",
        rules_block=rules_block,
        banned_block=banned_block,
        tonality_block=tonality_block,
        language_block=language_block,
    )

    result, tokens = await complete(
        SYSTEM,
        user_prompt,
        temperature=rules_config["temperature"],
        max_tokens=max_tok,
    )

    return {
        "content":    result,
        "tokensUsed": tokens,
        "agent":      "humanizer",
        "intensity":  intensity,
    }
