"""Agent 4 — Humanization Engine: makes content sound naturally human.

v2.0 — Aggressive false negative removal + deterministic cleanup pass.
"""
from services.llm import complete
from services.text_cleaner import clean_ai_patterns, detect_all_patterns, detect_false_negatives
import logging

log = logging.getLogger("ai-engine.humanizer")

SYSTEM = """You are a master editor who transforms AI-generated content into naturally human prose.

CORE MISSION:
Make content feel like it was written by a thoughtful, experienced professional —
not generated by AI. Preserve all facts, data, and strategic meaning.
Never fabricate information, statistics, or anecdotes.

═══════════════════════════════════════════════════════════════
CRITICAL RULE — FALSE NEGATIVES ARE FORBIDDEN
═══════════════════════════════════════════════════════════════

A "false negative" is when you say what something is NOT, only to then say what it IS.
This is the #1 dead giveaway of AI writing. ELIMINATE all instances.

❌ FORBIDDEN PATTERNS — never use these:

  "It's not just X, it's Y"
  "This isn't just about X, it's about Y"
  "It's not merely X, it's Y"
  "Not only does it X, but it also Y"
  "This is more than just X"
  "Rather than being X, it's Y"
  "Far from being X, it's Y"
  "This isn't your typical X"
  "It's less about X and more about Y"
  "Not a X, but a Y"

✅ INSTEAD — state the positive claim directly:

  BAD:  "Blockchain isn't just about crypto, it's about trust."
  GOOD: "Blockchain builds trust through cryptography."

  BAD:  "This isn't just a trend, it's a revolution."
  GOOD: "This is a revolution."

  BAD:  "Not only does it scale, but it also secures."
  GOOD: "It scales and secures."

  BAD:  "It's more than just a feature — it's a strategy."
  GOOD: "This feature drives the strategy."

RULE: If you catch yourself writing "not just", "not merely", "not only",
"isn't just", "more than just", "not about X, about Y" — STOP and rewrite
as a direct assertion.
"""

# ─── AI Phrase Blacklist ──────────────────────────────────────────────────────

BANNED_AI_PHRASES = [
    # False negatives (HIGHEST PRIORITY)
    "It's not just",
    "This isn't just",
    "It's not merely",
    "It's not only",
    "Not only",
    "More than just",
    "Far from being",
    "Rather than being",
    "Isn't your typical",
    "Less about",
    "It's not about",

    # Opening clichés
    "In today's fast-paced world",
    "In today's rapidly evolving",
    "In an era of",
    "In the age of",
    "In the realm of",
    "In the world of",
    "In the landscape of",
    "It is important to note",
    "It's worth noting that",
    "It goes without saying",
    "Needless to say",
    "When it comes to",
    "At its core",
    "At the heart of",

    # Transitions
    "In conclusion",
    "To summarize",
    "To recap",
    "In summary",
    "As we can see",
    "As mentioned above",
    "As previously discussed",
    "Furthermore",
    "Moreover",
    "Additionally",
    "In addition to this",
    "Consequently",
    "That being said",
    "With that in mind",

    # Corporate buzzwords
    "Game-changing",
    "Groundbreaking",
    "Revolutionary",
    "Transformative",
    "Disruptive",
    "Unprecedented",
    "Paradigm shift",
    "Synergy",
    "Ecosystem",
    "Leverage",
    "Utilize",
    "Operationalize",
    "Empower",
    "Facilitate",
    "Circle back",
    "Touch base",
    "Move the needle",
    "Low-hanging fruit",
    "Boil the ocean",
    "Peel back the layers",
    "Unpack",
    "Double-click on",
    "Dive deep",
    "Deep dive",

    # AI tells
    "Robust",
    "Seamless",
    "Holistic",
    "Cutting-edge",
    "State-of-the-art",
    "Best-in-class",
    "World-class",
    "Best practices",
    "Delve into",
    "Nuanced understanding",
    "Comprehensive overview",
    "Tapestry",
    "At the end of the day",
    "The reality is",
    "It's no secret that",
    "Navigate the complexities",
    "Unlock the power",
    "Harness the power",

    # Enthusiasm tells
    "Excited to share",
    "Thrilled to announce",
    "Delighted to present",
    "I am pleased to",
    "We are excited to",
]

# ─── Intensity Instructions ───────────────────────────────────────────────────

INTENSITY_RULES = {
    "light": {
        "description": "Minimal changes — surgical removal of AI tells only.",
        "rules": [
            "Remove ONLY the most obvious AI clichés from the banned list",
            "Eliminate ALL false negatives (not just/not merely/not only patterns)",
            "Keep sentence structure and rhythm largely intact",
            "Preserve all formatting, headings, and paragraph breaks",
            "Do NOT restructure — only spot-fix robotic phrases",
        ],
        "temperature": 0.5,
        "second_pass": False,
    },
    "medium": {
        "description": "Balanced humanization — natural flow with preserved structure.",
        "rules": [
            "Remove ALL banned AI phrases — replace with natural, specific alternatives",
            "ELIMINATE every false negative — convert to direct positive assertions",
            "Vary sentence lengths — mix short (5-8 words) with longer ones",
            "Add subtle rhythm variation — not every paragraph the same length",
            "Use contractions naturally (it's, you'll, we're) — but not forced",
            "Replace generic adjectives with specific, concrete ones",
            "Occasional conversational aside is fine (e.g., 'Here's the thing:')",
            "Maintain professional tone throughout",
            "Do not add fabricated details",
        ],
        "temperature": 0.65,
        "second_pass": True,
    },
    "aggressive": {
        "description": "Maximum humanization — rewrite for authentic human voice.",
        "rules": [
            "Substantially rewrite for naturalness — don't just swap phrases",
            "ZERO tolerance for false negatives — every 'not just X, it's Y' must become direct assertion",
            "Dramatically vary sentence lengths and structures throughout",
            "Break some grammar rules intentionally for voice (fragments are fine)",
            "Add micro-observations or brief qualifiers (e.g., 'at least in my experience')",
            "Use casual asides sparingly: 'honestly,' 'look,' 'here's the thing'",
            "Mix active and passive voice naturally — don't force everything active",
            "End thoughts abruptly sometimes — humans trail off",
            "Remove ALL corporate enthusiasm — no 'excited to share' etc.",
            "Replace 'A is B' reductive statements with nuanced phrasing",
            "Cut all filler openers and transitions — just jump to the point",
            "Result should feel like a thoughtful person wrote it from scratch",
        ],
        "temperature": 0.72,
        "second_pass": True,
    },
}

# ─── Language-Specific Rules ──────────────────────────────────────────────────

LANGUAGE_RULES = {
    "Hindi": "Apply humanization rules while writing in Hindi. Use natural Hindi idioms and phrasing. Avoid direct English translations.",
    "Hinglish": (
        "Content is in Hinglish (Hindi-English mix). "
        "Humanize in a way that feels natural to Indian professionals — "
        "casual Hindi expressions mixed with English are expected and welcome."
    ),
    "Spanish": "Apply humanization in Spanish. Use natural Spanish phrasing and avoid direct translations from English.",
    "French": "Apply humanization in French. Use natural French phrasing.",
}

# ─── Tonality Integration ─────────────────────────────────────────────────────

TONALITY_HUMANIZE_RULES = {
    "angry":      "Let measured indignation show through word choice — sharp edges, not explosive.",
    "frustrated": "Slight exasperation in sentence rhythm — shorter, more clipped phrasing.",
    "excited":    "Genuine energy — varied punctuation, some short punchy sentences.",
    "confident":  "Declarative statements — minimal hedging, direct assertions.",
    "curious":    "Questions and wondering — invite the reader to think alongside you.",
    "empathetic": "Warmer language — 'I understand...', 'Many of us have...'",
    "playful":    "Light wordplay, the occasional unexpected word choice.",
    "serious":    "Measured pacing, weighty words — no lightness or humor.",
}

# ─── Prompt Template ──────────────────────────────────────────────────────────

USER_TEMPLATE = """Humanize the following content.

CONTENT:
{content}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HUMANIZATION INTENSITY: {intensity_upper}
{description}

RULES TO APPLY:
{rules_block}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{detection_block}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
BANNED AI PHRASES — eliminate every instance:
{banned_block}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{tonality_block}
{language_block}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ABSOLUTE RULES:
- Keep ALL facts, statistics, names, and data exactly as they are
- Do NOT add invented anecdotes, statistics, or claims
- Do NOT reduce total content length by more than 10%
- Preserve the overall structure (headings, sections, key points)
- CRITICAL: Zero false negatives — no "not just X, it's Y" patterns

OUTPUT: Write only the humanized content. No commentary, no labels."""


# ─── Second Pass Prompt (for stubborn false negatives) ────────────────────────

SECOND_PASS_SYSTEM = """You are a final-pass editor whose sole job is to eliminate FALSE NEGATIVES.

A false negative is any construction like:
  - "not just X, it's Y"
  - "isn't merely X, it's Y"
  - "not only X, but also Y"
  - "more than just X"
  - "not about X, it's about Y"

These are AI writing tells. Convert every one into a DIRECT ASSERTION.

Examples of fixes:
  BAD:  "Blockchain isn't just about crypto — it's about trust."
  GOOD: "Blockchain is about trust, not just crypto." ❌ (still uses "not just")
  GOOD: "Blockchain enables trust. Crypto is one application." ✅

  BAD:  "Not only does it scale, but it also secures."
  GOOD: "It scales and secures." ✅

  BAD:  "This is more than just a product."
  GOOD: "This product changes how you work." ✅

RULES:
1. Keep all facts, data, structure, and formatting intact
2. Only rewrite sentences containing false negatives
3. Preserve length within 5%
4. Output only the fixed content — no commentary
"""

# ─── Detection Block Builder ──────────────────────────────────────────────────

def _build_detection_block(content: str) -> str:
    """
    Build detection warnings for LLM based on actual patterns found.
    Helps the LLM focus on real issues.
    """
    detections = detect_all_patterns(content)
    
    if detections["total_issues"] == 0:
        return "PRE-SCAN: No obvious AI patterns detected. Focus on natural voice."
    
    lines = ["🚨 PRE-SCAN DETECTED THESE ISSUES — FIX ALL OF THEM:"]
    
    if detections["false_negative_count"] > 0:
        false_negs = detect_false_negatives(content)
        examples = [f"'{f['match']}'" for f in false_negs[:3]]
        lines.append(
            f"  ⚠️  FALSE NEGATIVES ({detections['false_negative_count']} found): {', '.join(examples)}"
        )
        lines.append("     → Convert each to a direct positive assertion.")
    
    if detections["ai_openings"] > 0:
        lines.append(f"  ⚠️  AI OPENING CLICHES ({detections['ai_openings']} found)")
        lines.append("     → Start with a specific observation, not 'In today's world...'")
    
    if detections["hedging"] > 0:
        lines.append(f"  ⚠️  HEDGING PHRASES ({detections['hedging']} found)")
        lines.append("     → State things directly. Delete 'It's worth noting...'")
    
    if detections["buzzwords"] > 0:
        lines.append(f"  ⚠️  BUZZWORDS ({detections['buzzwords']} found)")
        lines.append("     → Replace with simple, specific words.")
    
    if detections["transitions"] > 0:
        lines.append(f"  ⚠️  AI TRANSITIONS ({detections['transitions']} found)")
        lines.append("     → Use natural connectors: 'But', 'So', 'And', 'Still'")
    
    return "\n".join(lines)


# ─── Agent Entry Point ────────────────────────────────────────────────────────

async def run(
    content:       str,
    intensity:     str  = "medium",
    tonality:      dict = None,
    language:      str  = "English",
    brand_phrases: list = None,
) -> dict:
    """
    Humanize content with aggressive false negative removal.
    
    Pipeline:
      1. Pre-scan for AI patterns (false negatives, cliches, buzzwords)
      2. LLM humanization with detection-aware prompt
      3. Deterministic cleanup pass (text_cleaner)
      4. Optional second pass if false negatives remain (medium/aggressive)
    
    Args:
        content:       Text to humanize
        intensity:     light | medium | aggressive
        tonality:      Tonality spectrum dict (from content wizard)
        language:      Output language
        brand_phrases: Additional brand-banned phrases to include
    """
    # ── Validate intensity ────────────────────────────────────────────────────
    if intensity not in INTENSITY_RULES:
        log.warning("Invalid intensity '%s' — defaulting to medium", intensity)
        intensity = "medium"

    rules_config = INTENSITY_RULES[intensity]

    # ── Pre-scan for patterns ─────────────────────────────────────────────────
    pre_detections = detect_all_patterns(content)
    detection_block = _build_detection_block(content)

    # ── Build banned phrases list ─────────────────────────────────────────────
    all_banned = list(BANNED_AI_PHRASES)
    if brand_phrases:
        for phrase in brand_phrases:
            if phrase not in all_banned:
                all_banned.append(phrase)

    banned_block = "\n".join(f"  • {p}" for p in all_banned)
    rules_block  = "\n".join(f"  {i+1}. {r}" for i, r in enumerate(rules_config["rules"]))

    # ── Tonality block ────────────────────────────────────────────────────────
    tonality_lines = []
    if tonality:
        active = [
            (k, v) for k, v in tonality.items()
            if v >= 5 and k in TONALITY_HUMANIZE_RULES
        ]
        active.sort(key=lambda x: x[1], reverse=True)

        if active:
            tonality_lines.append("TONALITY TO REFLECT IN HUMANIZATION:")
            for tone, val in active[:4]:
                rule = TONALITY_HUMANIZE_RULES[tone]
                tonality_lines.append(f"  • {tone.upper()} ({val}/10): {rule}")

    tonality_block = "\n".join(tonality_lines) if tonality_lines else ""

    # ── Language block ────────────────────────────────────────────────────────
    lang_instruction = LANGUAGE_RULES.get(language, "")
    language_block = (
        f"LANGUAGE NOTE: {lang_instruction}"
        if lang_instruction
        else f"Language: {language} — apply all rules in this language."
    )

    # ── Token budget ──────────────────────────────────────────────────────────
    content_words = len(content.split())
    max_tok = min(int(content_words * 1.5) + 600, 6000)

    log.info(
        "Humanizer start | intensity=%s | words=%d | lang=%s | "
        "pre_issues=%d (false_negs=%d) | tonality_active=%s",
        intensity, content_words, language,
        pre_detections["total_issues"],
        pre_detections["false_negative_count"],
        [k for k, v in (tonality or {}).items() if v >= 5],
    )

    # ── Pass 1: LLM Humanization ──────────────────────────────────────────────
    user_prompt = USER_TEMPLATE.format(
        content=content,
        intensity_upper=intensity.upper(),
        description=f"Goal: {rules_config['description']}",
        rules_block=rules_block,
        detection_block=detection_block,
        banned_block=banned_block,
        tonality_block=tonality_block,
        language_block=language_block,
    )

    humanized, tokens_p1 = await complete(
        SYSTEM,
        user_prompt,
        temperature=rules_config["temperature"],
        max_tokens=max_tok,
    )

    total_tokens = tokens_p1

    # ── Pass 2: Deterministic Cleanup ─────────────────────────────────────────
    cleanup_result = clean_ai_patterns(humanized, intensity=intensity)
    humanized = cleanup_result["content"]

    # ── Pass 3: Second LLM Pass (only if false negatives remain) ─────────────
    post_scan = detect_false_negatives(humanized)
    tokens_p2 = 0
    second_pass_run = False

    if rules_config["second_pass"] and len(post_scan) > 0:
        log.info(
            "Second pass triggered | remaining_false_negs=%d",
            len(post_scan)
        )
        second_pass_run = True

        second_pass_user = f"""The text below still contains {len(post_scan)} false negative(s).

DETECTED PATTERNS TO FIX:
{chr(10).join(f"  - '{f['match']}'" for f in post_scan[:5])}

Rewrite ONLY the sentences containing these patterns.
Convert each to a direct positive assertion.
Keep everything else unchanged.

TEXT:
{humanized}

Output only the fixed text."""

        humanized_p2, tokens_p2 = await complete(
            SECOND_PASS_SYSTEM,
            second_pass_user,
            temperature=0.5,
            max_tokens=max_tok,
        )

        # Only use second pass if it actually improved things
        p2_scan = detect_false_negatives(humanized_p2)
        if len(p2_scan) < len(post_scan):
            humanized = humanized_p2
            # Re-run cleanup on second pass output
            cleanup_result2 = clean_ai_patterns(humanized, intensity=intensity)
            humanized = cleanup_result2["content"]
        else:
            log.warning("Second pass did not improve — using first pass result")

        total_tokens += tokens_p2

    # ── Final metrics ─────────────────────────────────────────────────────────
    final_detections = detect_all_patterns(humanized)
    
    pre_total  = pre_detections["total_issues"]
    post_total = final_detections["total_issues"]
    reduction_pct = round(
        ((pre_total - post_total) / pre_total * 100) if pre_total > 0 else 100.0,
        1,
    )

    log.info(
        "Humanizer complete | intensity=%s | tokens=%d (p1=%d, p2=%d) | "
        "pre_issues=%d | post_issues=%d | reduction=%.1f%% | "
        "false_negs: %d → %d | second_pass=%s",
        intensity, total_tokens, tokens_p1, tokens_p2,
        pre_total, post_total, reduction_pct,
        pre_detections["false_negative_count"],
        final_detections["false_negative_count"],
        second_pass_run,
    )

    return {
        "content":    humanized,
        "tokensUsed": total_tokens,
        "agent":      "humanizer",
        "intensity":  intensity,
        "metadata": {
            "pre_issues":           pre_total,
            "post_issues":          post_total,
            "reduction_percent":    reduction_pct,
            "false_negatives_pre":  pre_detections["false_negative_count"],
            "false_negatives_post": final_detections["false_negative_count"],
            "second_pass_run":      second_pass_run,
            "detections_before":    cleanup_result["detections"]["before"],
            "detections_after":     cleanup_result["detections"]["after"],
        },
    }
